# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: check-deps
        name: Check for unlocked dependencies
        always_run: true
        pass_filenames: false
        language: system
        entry: "mix"
        args: ["deps.get"]
      - id: format
        name: Elixir Format
        files: ".*\\.exs?"
        language: system
        entry: "mix"
        args: ["format"]
      - id: credo
        name: Check Elixir code style with credo
        files: ".*\\.exs?"
        language: system
        entry: "mix"
        args: ["credo", "-a"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
